name: Carga de datos desde archivos sql

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: copy file via ssh password
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: "tests/a.txt,tests/b.txt"
            target: /home/ec2-user/


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker cp "C:\Users\v\Desktop\create.sql" postgresql-dev:/home/ec2-user/
            docker exec -i postgresql-dev psql -U POSTGRES_USER=${{ secrets.POSTGRES_USER }} -d POSTGRES_DB=${{ secrets.POSTGRES_DB }} -f /home/ec2-user/create.sql
