name: Carga de datos desde archivos SQL

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Copiar archivo SQL a EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "create.sql"  # Asegúrate de que este archivo está en la raíz del repo
          target: /home/ec2-user/

      - name: Ejecutar SQL dentro del contenedor PostgreSQL
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker cp /home/ec2-user/create.sql postgresql-dev:/home/ec2-user/create.sql
            docker exec -i postgresql-dev \
              psql -U ${{ secrets.POSTGRES_USER }} \
                   -d ${{ secrets.POSTGRES_DB }} \
                   -f /home/ec2-user/create.sql
